AWSTemplateFormatVersion: 2010-09-09
Description: TU 2k21 Game Bot

Transform:
- AWS::Serverless-2016-10-31

Resources:
  gameBot:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: app/
      Handler: dist/handlers/game-bot.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 2
      Role: "arn:aws:iam::269164092502:role/TU2k21-Bot-Execution-Role"
      Events:
        HealthcheckApi:
          Type: Api
          Properties:
            Path: /healthcheck
            Method: GET
        GameBotApi:
          Type: Api
          Properties:
            Path: /bot
            Method: POST

Outputs:
  HealthcheckEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/healthcheck"
  BotEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bot"
